name: Build Next.js web application
on: push
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build project assests
        run: npm run build
